// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module capture_objects (
        ap_ready,
        link_in_0_V_read,
        link_in_1_V_read,
        link_in_2_V_read,
        link_in_3_V_read,
        link_in_4_V_read,
        link_in_5_V_read,
        link_in_6_V_read,
        link_in_7_V_read,
        link_in_8_V_read,
        link_in_9_V_read,
        link_in_10_V_read,
        link_in_11_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31,
        ap_return_32,
        ap_return_33,
        ap_return_34,
        ap_return_35,
        ap_return_36,
        ap_return_37,
        ap_return_38,
        ap_return_39,
        ap_return_40,
        ap_return_41,
        ap_return_42,
        ap_return_43,
        ap_return_44,
        ap_return_45,
        ap_return_46,
        ap_return_47,
        ap_return_48,
        ap_return_49,
        ap_return_50,
        ap_return_51,
        ap_return_52,
        ap_return_53,
        ap_return_54,
        ap_return_55,
        ap_return_56,
        ap_return_57,
        ap_return_58,
        ap_return_59
);


output   ap_ready;
input  [191:0] link_in_0_V_read;
input  [191:0] link_in_1_V_read;
input  [191:0] link_in_2_V_read;
input  [191:0] link_in_3_V_read;
input  [191:0] link_in_4_V_read;
input  [191:0] link_in_5_V_read;
input  [191:0] link_in_6_V_read;
input  [191:0] link_in_7_V_read;
input  [191:0] link_in_8_V_read;
input  [191:0] link_in_9_V_read;
input  [191:0] link_in_10_V_read;
input  [191:0] link_in_11_V_read;
output  [9:0] ap_return_0;
output  [9:0] ap_return_1;
output  [9:0] ap_return_2;
output  [9:0] ap_return_3;
output  [9:0] ap_return_4;
output  [9:0] ap_return_5;
output  [9:0] ap_return_6;
output  [9:0] ap_return_7;
output  [9:0] ap_return_8;
output  [9:0] ap_return_9;
output  [9:0] ap_return_10;
output  [9:0] ap_return_11;
output  [9:0] ap_return_12;
output  [9:0] ap_return_13;
output  [9:0] ap_return_14;
output  [9:0] ap_return_15;
output  [9:0] ap_return_16;
output  [9:0] ap_return_17;
output  [9:0] ap_return_18;
output  [9:0] ap_return_19;
output  [9:0] ap_return_20;
output  [9:0] ap_return_21;
output  [9:0] ap_return_22;
output  [9:0] ap_return_23;
output  [9:0] ap_return_24;
output  [9:0] ap_return_25;
output  [9:0] ap_return_26;
output  [9:0] ap_return_27;
output  [9:0] ap_return_28;
output  [9:0] ap_return_29;
output  [9:0] ap_return_30;
output  [9:0] ap_return_31;
output  [9:0] ap_return_32;
output  [9:0] ap_return_33;
output  [9:0] ap_return_34;
output  [9:0] ap_return_35;
output  [9:0] ap_return_36;
output  [9:0] ap_return_37;
output  [9:0] ap_return_38;
output  [9:0] ap_return_39;
output  [9:0] ap_return_40;
output  [9:0] ap_return_41;
output  [9:0] ap_return_42;
output  [9:0] ap_return_43;
output  [9:0] ap_return_44;
output  [9:0] ap_return_45;
output  [9:0] ap_return_46;
output  [9:0] ap_return_47;
output  [9:0] ap_return_48;
output  [9:0] ap_return_49;
output  [9:0] ap_return_50;
output  [9:0] ap_return_51;
output  [9:0] ap_return_52;
output  [9:0] ap_return_53;
output  [9:0] ap_return_54;
output  [9:0] ap_return_55;
output  [9:0] ap_return_56;
output  [9:0] ap_return_57;
output  [9:0] ap_return_58;
output  [9:0] ap_return_59;

assign ap_ready = 1'b1;

assign ap_return_0 = {{link_in_0_V_read[41:32]}};

assign ap_return_1 = {{link_in_0_V_read[73:64]}};

assign ap_return_10 = {{link_in_2_V_read[41:32]}};

assign ap_return_11 = {{link_in_2_V_read[73:64]}};

assign ap_return_12 = {{link_in_2_V_read[105:96]}};

assign ap_return_13 = {{link_in_2_V_read[137:128]}};

assign ap_return_14 = {{link_in_2_V_read[169:160]}};

assign ap_return_15 = {{link_in_3_V_read[41:32]}};

assign ap_return_16 = {{link_in_3_V_read[73:64]}};

assign ap_return_17 = {{link_in_3_V_read[105:96]}};

assign ap_return_18 = {{link_in_3_V_read[137:128]}};

assign ap_return_19 = {{link_in_3_V_read[169:160]}};

assign ap_return_2 = {{link_in_0_V_read[105:96]}};

assign ap_return_20 = {{link_in_4_V_read[41:32]}};

assign ap_return_21 = {{link_in_4_V_read[73:64]}};

assign ap_return_22 = {{link_in_4_V_read[105:96]}};

assign ap_return_23 = {{link_in_4_V_read[137:128]}};

assign ap_return_24 = {{link_in_4_V_read[169:160]}};

assign ap_return_25 = {{link_in_5_V_read[41:32]}};

assign ap_return_26 = {{link_in_5_V_read[73:64]}};

assign ap_return_27 = {{link_in_5_V_read[105:96]}};

assign ap_return_28 = {{link_in_5_V_read[137:128]}};

assign ap_return_29 = {{link_in_5_V_read[169:160]}};

assign ap_return_3 = {{link_in_0_V_read[137:128]}};

assign ap_return_30 = {{link_in_6_V_read[41:32]}};

assign ap_return_31 = {{link_in_6_V_read[73:64]}};

assign ap_return_32 = {{link_in_6_V_read[105:96]}};

assign ap_return_33 = {{link_in_6_V_read[137:128]}};

assign ap_return_34 = {{link_in_6_V_read[169:160]}};

assign ap_return_35 = {{link_in_7_V_read[41:32]}};

assign ap_return_36 = {{link_in_7_V_read[73:64]}};

assign ap_return_37 = {{link_in_7_V_read[105:96]}};

assign ap_return_38 = {{link_in_7_V_read[137:128]}};

assign ap_return_39 = {{link_in_7_V_read[169:160]}};

assign ap_return_4 = {{link_in_0_V_read[169:160]}};

assign ap_return_40 = {{link_in_8_V_read[41:32]}};

assign ap_return_41 = {{link_in_8_V_read[73:64]}};

assign ap_return_42 = {{link_in_8_V_read[105:96]}};

assign ap_return_43 = {{link_in_8_V_read[137:128]}};

assign ap_return_44 = {{link_in_8_V_read[169:160]}};

assign ap_return_45 = {{link_in_9_V_read[41:32]}};

assign ap_return_46 = {{link_in_9_V_read[73:64]}};

assign ap_return_47 = {{link_in_9_V_read[105:96]}};

assign ap_return_48 = {{link_in_9_V_read[137:128]}};

assign ap_return_49 = {{link_in_9_V_read[169:160]}};

assign ap_return_5 = {{link_in_1_V_read[41:32]}};

assign ap_return_50 = {{link_in_10_V_read[41:32]}};

assign ap_return_51 = {{link_in_10_V_read[73:64]}};

assign ap_return_52 = {{link_in_10_V_read[105:96]}};

assign ap_return_53 = {{link_in_10_V_read[137:128]}};

assign ap_return_54 = {{link_in_10_V_read[169:160]}};

assign ap_return_55 = {{link_in_11_V_read[41:32]}};

assign ap_return_56 = {{link_in_11_V_read[73:64]}};

assign ap_return_57 = {{link_in_11_V_read[105:96]}};

assign ap_return_58 = {{link_in_11_V_read[137:128]}};

assign ap_return_59 = {{link_in_11_V_read[169:160]}};

assign ap_return_6 = {{link_in_1_V_read[73:64]}};

assign ap_return_7 = {{link_in_1_V_read[105:96]}};

assign ap_return_8 = {{link_in_1_V_read[137:128]}};

assign ap_return_9 = {{link_in_1_V_read[169:160]}};

endmodule //capture_objects
