// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module swap (
        ap_ready,
        x_V_read,
        y_V_read,
        ap_return_0,
        ap_return_1
);


output   ap_ready;
input  [9:0] x_V_read;
input  [9:0] y_V_read;
output  [9:0] ap_return_0;
output  [9:0] ap_return_1;

assign ap_ready = 1'b1;

assign ap_return_0 = y_V_read;

assign ap_return_1 = x_V_read;

endmodule //swap
